# Generated by Django 3.1.4 on 2024-11-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20241118_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='used',
            new_name='user',
        ),
    ]
